
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-23T19:01:26+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "a35c59769c943cd5ace1dc1602999674e2a51ea2",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
