# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aiomagra/taptap.proto
"""Generated protocol buffer code."""
from google.protobuf import (
  descriptor as _descriptor,
  descriptor_pool as _descriptor_pool,
  symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61iomagra/taptap.proto\x12\x08vemmiopb\"\x1b\n\x0cTapTapReport\x12\x0b\n\x03num\x18\x01 \x01(\x05\x42=\n-com.vemmio.ha.integration.vemmio.rpc.vemmiopbP\x01Z\n./vemmiopbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiomagra.taptap_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS is False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.vemmio.ha.integration.vemmio.rpc.vemmiopbP\001Z\n./vemmiopb'
  _TAPTAPREPORT._serialized_start=35
  _TAPTAPREPORT._serialized_end=62
# @@protoc_insertion_point(module_scope)
