# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mvbSniffer/v1/mvbSniffer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mvbSniffer/v1/mvbSniffer.proto',
  package='mvbSniffer',
  syntax='proto3',
  serialized_options=_b('Z\rmvbSniffer/v1'),
  serialized_pb=_b('\n\x1emvbSniffer/v1/mvbSniffer.proto\x12\nmvbSniffer\"\x12\n\x10\x43onfigurationSet\"\x1a\n\x18\x43onfigurationSetResponse\"\x12\n\x10\x43onfigurationGet\"\x1a\n\x18\x43onfigurationGetResponse\"\x17\n\x15\x43onfigurationDescribe\"\x1f\n\x1d\x43onfigurationDescribeResponse\"\x14\n\x12\x46unctionControlGet\"/\n\x12\x46unctionControlSet\x12\x19\n\x11generator_pattern\x18\x01 \x01(\t\"\x1c\n\x1a\x46unctionControlGetResponse\"\x1c\n\x1a\x46unctionControlSetResponse\"a\n\nFilterMask\x12\x13\n\x0b\x66_code_mask\x18\x01 \x01(\r\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\r\x12\x0c\n\x04mask\x18\x03 \x01(\r\x12\x1f\n\x17include_timedout_frames\x18\x04 \x01(\x08\"<\n\x12StreamControlStart\x12&\n\x06\x66ilter\x18\x01 \x03(\x0b\x32\x16.mvbSniffer.FilterMaskB\x0fZ\rmvbSniffer/v1b\x06proto3')
)




_CONFIGURATIONSET = _descriptor.Descriptor(
  name='ConfigurationSet',
  full_name='mvbSniffer.ConfigurationSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=64,
)


_CONFIGURATIONSETRESPONSE = _descriptor.Descriptor(
  name='ConfigurationSetResponse',
  full_name='mvbSniffer.ConfigurationSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=92,
)


_CONFIGURATIONGET = _descriptor.Descriptor(
  name='ConfigurationGet',
  full_name='mvbSniffer.ConfigurationGet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=112,
)


_CONFIGURATIONGETRESPONSE = _descriptor.Descriptor(
  name='ConfigurationGetResponse',
  full_name='mvbSniffer.ConfigurationGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=140,
)


_CONFIGURATIONDESCRIBE = _descriptor.Descriptor(
  name='ConfigurationDescribe',
  full_name='mvbSniffer.ConfigurationDescribe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=165,
)


_CONFIGURATIONDESCRIBERESPONSE = _descriptor.Descriptor(
  name='ConfigurationDescribeResponse',
  full_name='mvbSniffer.ConfigurationDescribeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=198,
)


_FUNCTIONCONTROLGET = _descriptor.Descriptor(
  name='FunctionControlGet',
  full_name='mvbSniffer.FunctionControlGet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=220,
)


_FUNCTIONCONTROLSET = _descriptor.Descriptor(
  name='FunctionControlSet',
  full_name='mvbSniffer.FunctionControlSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='generator_pattern', full_name='mvbSniffer.FunctionControlSet.generator_pattern', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=269,
)


_FUNCTIONCONTROLGETRESPONSE = _descriptor.Descriptor(
  name='FunctionControlGetResponse',
  full_name='mvbSniffer.FunctionControlGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=299,
)


_FUNCTIONCONTROLSETRESPONSE = _descriptor.Descriptor(
  name='FunctionControlSetResponse',
  full_name='mvbSniffer.FunctionControlSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=329,
)


_FILTERMASK = _descriptor.Descriptor(
  name='FilterMask',
  full_name='mvbSniffer.FilterMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f_code_mask', full_name='mvbSniffer.FilterMask.f_code_mask', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='mvbSniffer.FilterMask.address', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask', full_name='mvbSniffer.FilterMask.mask', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='include_timedout_frames', full_name='mvbSniffer.FilterMask.include_timedout_frames', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=428,
)


_STREAMCONTROLSTART = _descriptor.Descriptor(
  name='StreamControlStart',
  full_name='mvbSniffer.StreamControlStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter', full_name='mvbSniffer.StreamControlStart.filter', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=490,
)

_STREAMCONTROLSTART.fields_by_name['filter'].message_type = _FILTERMASK
DESCRIPTOR.message_types_by_name['ConfigurationSet'] = _CONFIGURATIONSET
DESCRIPTOR.message_types_by_name['ConfigurationSetResponse'] = _CONFIGURATIONSETRESPONSE
DESCRIPTOR.message_types_by_name['ConfigurationGet'] = _CONFIGURATIONGET
DESCRIPTOR.message_types_by_name['ConfigurationGetResponse'] = _CONFIGURATIONGETRESPONSE
DESCRIPTOR.message_types_by_name['ConfigurationDescribe'] = _CONFIGURATIONDESCRIBE
DESCRIPTOR.message_types_by_name['ConfigurationDescribeResponse'] = _CONFIGURATIONDESCRIBERESPONSE
DESCRIPTOR.message_types_by_name['FunctionControlGet'] = _FUNCTIONCONTROLGET
DESCRIPTOR.message_types_by_name['FunctionControlSet'] = _FUNCTIONCONTROLSET
DESCRIPTOR.message_types_by_name['FunctionControlGetResponse'] = _FUNCTIONCONTROLGETRESPONSE
DESCRIPTOR.message_types_by_name['FunctionControlSetResponse'] = _FUNCTIONCONTROLSETRESPONSE
DESCRIPTOR.message_types_by_name['FilterMask'] = _FILTERMASK
DESCRIPTOR.message_types_by_name['StreamControlStart'] = _STREAMCONTROLSTART
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigurationSet = _reflection.GeneratedProtocolMessageType('ConfigurationSet', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONSET,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.ConfigurationSet)
  ))
_sym_db.RegisterMessage(ConfigurationSet)

ConfigurationSetResponse = _reflection.GeneratedProtocolMessageType('ConfigurationSetResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONSETRESPONSE,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.ConfigurationSetResponse)
  ))
_sym_db.RegisterMessage(ConfigurationSetResponse)

ConfigurationGet = _reflection.GeneratedProtocolMessageType('ConfigurationGet', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONGET,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.ConfigurationGet)
  ))
_sym_db.RegisterMessage(ConfigurationGet)

ConfigurationGetResponse = _reflection.GeneratedProtocolMessageType('ConfigurationGetResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONGETRESPONSE,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.ConfigurationGetResponse)
  ))
_sym_db.RegisterMessage(ConfigurationGetResponse)

ConfigurationDescribe = _reflection.GeneratedProtocolMessageType('ConfigurationDescribe', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONDESCRIBE,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.ConfigurationDescribe)
  ))
_sym_db.RegisterMessage(ConfigurationDescribe)

ConfigurationDescribeResponse = _reflection.GeneratedProtocolMessageType('ConfigurationDescribeResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONDESCRIBERESPONSE,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.ConfigurationDescribeResponse)
  ))
_sym_db.RegisterMessage(ConfigurationDescribeResponse)

FunctionControlGet = _reflection.GeneratedProtocolMessageType('FunctionControlGet', (_message.Message,), dict(
  DESCRIPTOR = _FUNCTIONCONTROLGET,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.FunctionControlGet)
  ))
_sym_db.RegisterMessage(FunctionControlGet)

FunctionControlSet = _reflection.GeneratedProtocolMessageType('FunctionControlSet', (_message.Message,), dict(
  DESCRIPTOR = _FUNCTIONCONTROLSET,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.FunctionControlSet)
  ))
_sym_db.RegisterMessage(FunctionControlSet)

FunctionControlGetResponse = _reflection.GeneratedProtocolMessageType('FunctionControlGetResponse', (_message.Message,), dict(
  DESCRIPTOR = _FUNCTIONCONTROLGETRESPONSE,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.FunctionControlGetResponse)
  ))
_sym_db.RegisterMessage(FunctionControlGetResponse)

FunctionControlSetResponse = _reflection.GeneratedProtocolMessageType('FunctionControlSetResponse', (_message.Message,), dict(
  DESCRIPTOR = _FUNCTIONCONTROLSETRESPONSE,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.FunctionControlSetResponse)
  ))
_sym_db.RegisterMessage(FunctionControlSetResponse)

FilterMask = _reflection.GeneratedProtocolMessageType('FilterMask', (_message.Message,), dict(
  DESCRIPTOR = _FILTERMASK,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.FilterMask)
  ))
_sym_db.RegisterMessage(FilterMask)

StreamControlStart = _reflection.GeneratedProtocolMessageType('StreamControlStart', (_message.Message,), dict(
  DESCRIPTOR = _STREAMCONTROLSTART,
  __module__ = 'mvbSniffer.v1.mvbSniffer_pb2'
  # @@protoc_insertion_point(class_scope:mvbSniffer.StreamControlStart)
  ))
_sym_db.RegisterMessage(StreamControlStart)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
