# Generated by Django 4.0 on 2022-09-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_rename_end_reason_empplacement_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='de',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='empplacement',
            name='position',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contract.contracttype'),
        ),
    ]
