# Generated by Django 4.0 on 2022-09-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_empplacement_position_alter_empposition_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empsalary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='empsalary',
            name='position',
        ),
    ]
