# Generated by Django 4.0 on 2022-09-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_echelon_grade'),
        ('contract', '0006_remove_empsalary_employee_remove_empsalary_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empsalary',
            old_name='total',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='empsalary',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='empsalary',
            name='position_salary',
        ),
        migrations.RemoveField(
            model_name='empsalary',
            name='transport',
        ),
        migrations.AddField(
            model_name='contract',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contract.category'),
        ),
        migrations.AddField(
            model_name='contract',
            name='echelon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='custom.echelon'),
        ),
        migrations.AddField(
            model_name='contract',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='custom.grade'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empsalary', to='contract.contract'),
        ),
    ]
