# Generated by Django 3.2 on 2023-03-10 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_alter_fidnumber_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0017_contract_file_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpContractToR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tor', models.TextField()),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_lock', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emptor', to='contract.contract')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emptor', to='employee.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
