
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-23T14:01:26+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "9cb6933bb31f46f190379c6714c40a5fa101d95b",
 "version": "1.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
