LEGAL_ENTITY = "LEGAL_ENTITY"
NATURAL_PERSON = "NATURAL_PERSON"
SUPPORTED_VERSIONS = [LEGAL_ENTITY, NATURAL_PERSON]
EBSI_DID_SPECS = {
    LEGAL_ENTITY: {
        "VERSION_ID": 0x01,
        "BYTE_LENGTH": 16,
    },
    NATURAL_PERSON: {"VERSION_ID": 0x02, "BYTE_LENGTH": 32},
}
