# Form implementation generated from reading ui file 'jupyter_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(319, 173)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_c = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_c.setChecked(True)
        self.checkBox_c.setObjectName("checkBox_c")
        self.verticalLayout.addWidget(self.checkBox_c)
        self.checkBox_v = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_v.setChecked(True)
        self.checkBox_v.setObjectName("checkBox_v")
        self.verticalLayout.addWidget(self.checkBox_v)
        self.checkBox_v2 = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_v2.setChecked(True)
        self.checkBox_v2.setObjectName("checkBox_v2")
        self.verticalLayout.addWidget(self.checkBox_v2)
        self.checkBox_a = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_a.setChecked(True)
        self.checkBox_a.setObjectName("checkBox_a")
        self.verticalLayout.addWidget(self.checkBox_a)
        self.checkBox_e = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_e.setChecked(True)
        self.checkBox_e.setObjectName("checkBox_e")
        self.verticalLayout.addWidget(self.checkBox_e)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Choix des représentations graphiques"))
        self.checkBox_c.setText(_translate("Dialog", "Chronogramme des positions"))
        self.checkBox_v.setText(_translate("Dialog", "Vecteurs vitesse"))
        self.checkBox_v2.setText(_translate("Dialog", "Vecteurs variation de vitesse"))
        self.checkBox_a.setText(_translate("Dialog", "Vecteurs accélération"))
        self.checkBox_e.setText(_translate("Dialog", "Énergies"))
