
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-24T13:55:28-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa4723f8e78aa52dc02859d45ce538464cee13ab",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
