# Generated by Django 2.2 on 2022-02-28 09:09

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import giant_plugins.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('filer', '0012_file_mime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCTA',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='featured_cta_featuredcta', serialize=False, to='cms.CMSPlugin')),
                ('external_url', models.URLField(blank=True, help_text='Overrides the internal link if set')),
                ('title', giant_plugins.utils.RichTextField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('cta_text', models.CharField(max_length=255)),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_cta_featuredcta_files', to='filer.File', verbose_name='File')),
                ('internal_link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cms.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
