# Generated by Django 4.0 on 2022-09-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_remove_area_study_program_delete_faculty_delete_area_and_more'),
        ('contract', '0004_remove_contract_category_remove_contract_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empplacement',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='custom.position'),
        ),
        migrations.AlterField(
            model_name='empposition',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empposition', to='custom.department'),
        ),
    ]
