# Generated by Django 4.0 on 2022-09-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_curempposition_curempdivision'),
        ('contract', '0007_rename_total_empsalary_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empsalary',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empsalary', to='employee.employee'),
        ),
    ]
