# Generated by Django 3.2 on 2022-12-08 01:00

import django.core.validators
from django.db import migrations, models
import settings_app.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_empposition_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=settings_app.upload_utils.upload_contract, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Attach ToR'),
        ),
    ]
