# Generated by Django 3.2 on 2023-02-14 04:12

import django.core.validators
from django.db import migrations, models
import settings_app.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_alter_organograma_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='file_end',
            field=models.FileField(blank=True, null=True, upload_to=settings_app.upload_utils.upload_contract_end, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Anekso'),
        ),
    ]
