# Generated by Django 4.0 on 2022-10-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_tcriteria_trainingcriteria_remove_unitcriteria_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcriteria',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
