# Generated by Django 4.0 on 2022-10-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_trainingplan_duration_trainingplan_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingemp',
            name='hashed',
        ),
        migrations.DeleteModel(
            name='TrainingSubject',
        ),
    ]
