# Generated by Django 4.0 on 2022-10-26 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0007_adninfo'),
        ('training', '0011_remove_trainingemp_hashed_delete_trainingsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingemp',
            name='diploma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingemp', to='custom.educationlevel'),
        ),
        migrations.AlterField(
            model_name='trainingemp',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingemp', to='custom.department'),
        ),
        migrations.AlterField(
            model_name='trainingemp',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingemp', to='custom.position'),
        ),
        migrations.AlterField(
            model_name='trainingemp',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingemp', to='custom.unit'),
        ),
    ]
