# Generated by Django 3.2 on 2023-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0032_trainingplan_is_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='is_update',
        ),
        migrations.AddField(
            model_name='trainingplangap',
            name='is_update',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
