# Generated by Django 4.0 on 2022-10-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0005_alter_employee_blood_alter_employee_father_and_more'),
        ('custom', '0006_position_code'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(blank=True, max_length=300, null=True, verbose_name='Kriteria')),
                ('obs', models.CharField(choices=[('Sim', 'Sim'), ('Lae', 'Lae')], max_length=6, null=True)),
                ('datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingemp', to='custom.department', verbose_name='Departamento')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingemp', to='employee.employee', verbose_name='Pessoal')),
            ],
        ),
        migrations.CreateModel(
            name='TYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(blank=True, max_length=300, null=True, verbose_name='Kriteria')),
                ('obs', models.CharField(choices=[('Sim', 'Sim'), ('Lae', 'Lae')], max_length=6, null=True)),
                ('datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='area',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='fund_amount',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='title',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.department', verbose_name='Departamentu'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Materia Formasaun'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.unit', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatin'),
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.AddField(
            model_name='unitcriteria',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitcriteria', to='training.trainingplan'),
        ),
        migrations.AddField(
            model_name='unitcriteria',
            name='training_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitcriteria', to='training.trainingemp', verbose_name='Pessoal'),
        ),
        migrations.AddField(
            model_name='unitcriteria',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='trainingemp',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingemp', to='training.trainingplan'),
        ),
        migrations.AddField(
            model_name='trainingemp',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingemp', to='custom.position', verbose_name='Pojisaun'),
        ),
        migrations.AddField(
            model_name='trainingemp',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingemp', to='custom.unit', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='trainingemp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='hrcriteria',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrcriteria', to='training.trainingplan'),
        ),
        migrations.AddField(
            model_name='hrcriteria',
            name='training_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrcriteria', to='training.trainingemp', verbose_name='Pessoal'),
        ),
        migrations.AddField(
            model_name='hrcriteria',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.tyear', verbose_name='Tinan'),
        ),
    ]
