# Generated by Django 3.2 on 2022-12-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20221210_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingemp',
            name='is_update',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
