# Generated by Django 3.2 on 2022-12-10 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_employee_pin'),
        ('training', '0021_rename_start_date_scholarshipempprogress_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipemp',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarshipemp', to='employee.employee', verbose_name='Pessoal'),
        ),
    ]
