# Generated by Django 3.2 on 2022-12-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_scholarshipplan_is_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipplan',
            name='is_update',
        ),
        migrations.AddField(
            model_name='scholarshipemp',
            name='is_update',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
