# Generated by Django 3.2 on 2023-03-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_traininggap'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggap',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
