# Generated by Django 3.2 on 2023-03-11 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0013_alter_unit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0029_traininggap_is_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlanGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('gap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traininggap', to='training.traininggap')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traininggap', to='training.trainingplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingdep', to='custom.department')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingdep', to='training.trainingplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
