# Generated by Django 3.2 on 2023-03-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0031_auto_20230312_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='is_update',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
