# Generated by Django 2.2 on 2022-06-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_width_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentwidthimage',
            name='credit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
