# Generated by Django 2.2 on 2022-06-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_width_image', '0002_contentwidthimage_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentwidthimage',
            name='caption',
            field=models.CharField(help_text='Add a caption to the image', max_length=255),
        ),
        migrations.AlterField(
            model_name='contentwidthimage',
            name='credit',
            field=models.CharField(max_length=255),
        ),
    ]
