
ALPHAVANTAGE = 'ALPHAVANTAGE'
QUANDL = 'QUANDL'

# available methods
REFRESH_SYMBOL = 'REFRESH_SYMBOL'

SYMBOL = 'SYMBOL'
EXCHANGE = 'EXCHANGE'
BASE_SYMBOL = 'BASE_SYMBOL'
QUOTE_SYMBOL = 'QUOTE_SYMBOL'

# db schema
TABLE = 'tb_'
