# Generated by Django 3.2.19 on 2023-06-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='anchor_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
