# Generated by Django 4.0 on 2022-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_category_is_dep_category_is_deputy_category_is_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_advisor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
