# Generated by Django 4.0 on 2022-09-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_category_is_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_advisor',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_dep',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deputy',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_eng',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_non_eng',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_unit',
        ),
    ]
