# Generated by Django 3.2 on 2022-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_remove_category_is_advisor_remove_category_is_dep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empposition',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
