
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-21T10:48:26-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "87cecdc35c5c42a924e82e9acbe65212db2a5fa9",
 "version": "0.1.0a95"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
