
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-13T21:26:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d8ca65053e34852a61e71a8feceb43e852f77d3",
 "version": "23.07.dev0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
