# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from boids_api.boids.base_model_ import Model
from boids_api.boids.boid import Boid
from boids_api.boids.pagination import Pagination
from boids_api import util

from boids_api.boids.boid import Boid  # noqa: E501
from boids_api.boids.pagination import Pagination  # noqa: E501

class BoidList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, values=None, pagination=None):  # noqa: E501
        """BoidList - a model defined in OpenAPI

        :param values: The values of this BoidList.  # noqa: E501
        :type values: List[Boid]
        :param pagination: The pagination of this BoidList.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {
            'values': List[Boid],
            'pagination': Pagination
        }

        self.attribute_map = {
            'values': 'values',
            'pagination': 'pagination'
        }

        self._values = values
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'BoidList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BoidList of this BoidList.  # noqa: E501
        :rtype: BoidList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def values(self):
        """Gets the values of this BoidList.


        :return: The values of this BoidList.
        :rtype: List[Boid]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this BoidList.


        :param values: The values of this BoidList.
        :type values: List[Boid]
        """
        if values is None:
            raise ValueError("Invalid value for `values`, must not be `None`")  # noqa: E501

        self._values = values

    @property
    def pagination(self):
        """Gets the pagination of this BoidList.


        :return: The pagination of this BoidList.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this BoidList.


        :param pagination: The pagination of this BoidList.
        :type pagination: Pagination
        """

        self._pagination = pagination
