
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-21T12:44:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c38ce8a759726982fe57ad32270f615c1fed6104",
 "version": "0.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
