# Generated by Django 4.0 on 2022-09-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='section',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='empplacement',
            old_name='section',
            new_name='department',
        ),
    ]
