# Generated by Django 4.0 on 2022-09-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_alter_empsalary_datetime_alter_empsalary_hashed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_dep',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deputy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_eng',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_non_eng',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_unit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
