# Generated by Django 3.2 on 2023-03-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_empcontracttor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empcontracttor',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emptor', to='contract.contract'),
        ),
    ]
