# (C) Copyright 2008-2023 Enthought, Inc., Austin, TX
# All rights reserved.
#
# This software is provided without warranty under the terms of the BSD
# license included in LICENSE.txt and may be redistributed only under
# the conditions described in the aforementioned license. The license
# is also available online at http://www.enthought.com/licenses/BSD.txt
#
# Thanks for using Enthought open source!

"""
Version information for this Apptools distribution.

This file is autogenerated by the Apptools setup.py script.
"""

#: The full version of the package, including a development suffix
#: for unreleased versions of the package.
version = "5.2.1"

#: The Git revision from which this release was made.
git_revision = "237c3195f37631b709dbb66a2e9e5959f4521e01"

#: Flag whether this is a final release
is_released = True
