# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import billing_pb2 as billing__pb2


class BillingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePaymentIntent = channel.unary_unary(
                '/batchx.billing.BillingService/CreatePaymentIntent',
                request_serializer=billing__pb2.CreatePaymentIntentRequest.SerializeToString,
                response_deserializer=billing__pb2.CreatePaymentIntentResponse.FromString,
                )
        self.ListCharges = channel.unary_unary(
                '/batchx.billing.BillingService/ListCharges',
                request_serializer=billing__pb2.ListChargesRequest.SerializeToString,
                response_deserializer=billing__pb2.ListChargesResponse.FromString,
                )


class BillingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePaymentIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCharges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePaymentIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePaymentIntent,
                    request_deserializer=billing__pb2.CreatePaymentIntentRequest.FromString,
                    response_serializer=billing__pb2.CreatePaymentIntentResponse.SerializeToString,
            ),
            'ListCharges': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCharges,
                    request_deserializer=billing__pb2.ListChargesRequest.FromString,
                    response_serializer=billing__pb2.ListChargesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'batchx.billing.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePaymentIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/batchx.billing.BillingService/CreatePaymentIntent',
            billing__pb2.CreatePaymentIntentRequest.SerializeToString,
            billing__pb2.CreatePaymentIntentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCharges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/batchx.billing.BillingService/ListCharges',
            billing__pb2.ListChargesRequest.SerializeToString,
            billing__pb2.ListChargesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
