# Generated by Django 4.0.8 on 2023-04-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsecuritypolicysettings',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='contentsecuritypolicysettings',
            name='CSP_CONNECT_SRC',
            field=models.TextField(default="'self' i.ytimg.com docs.google.com www.youtube-nocookie.com analytics.womensdeclaration.com",
                                   help_text='Restricts the URLs which can be loaded using script interfaces. Restricted APIs: <a>, ping, fetch, XMLHttprequest, WebSocket, EventSource, Navigator.sendBeacon.'),
        ),
        migrations.AlterField(
            model_name='contentsecuritypolicysettings',
            name='CSP_FONT_SRC',
            field=models.TextField(default="'self' i.ytimg.com docs.google.com www.youtube-nocookie.com analytics.womensdeclaration.com", help_text='Specifies valid sources for fonts loaded using @font-face.'),
        ),
        migrations.AlterField(
            model_name='contentsecuritypolicysettings',
            name='CSP_FRAME_SRC',
            field=models.TextField(default="'self' i.ytimg.com docs.google.com www.youtube-nocookie.com analytics.womensdeclaration.com", help_text='Specifies valid sources for <frame> and <iframe> elements.'),
        ),
        migrations.AlterField(
            model_name='contentsecuritypolicysettings',
            name='CSP_IMG_SRC',
            field=models.TextField(default="'self' i.ytimg.com docs.google.com www.youtube-nocookie.com analytics.womensdeclaration.com", help_text='Specifies valid sources for images and favicons.'),
        ),
        migrations.AlterField(
            model_name='contentsecuritypolicysettings',
            name='CSP_SCRIPT_SRC',
            field=models.TextField(default="'self' 'unsafe-inline' i.ytimg.com docs.google.com www.youtube-nocookie.com analytics.womensdeclaration.com",
                                   help_text='Specifies valid sources for javascript. It would be a security win to disallow unsafe-inline in the future by using a nonce-source/hash-source for any inline scripts.'),
        ),
        migrations.AlterField(
            model_name='contentsecuritypolicysettings',
            name='CSP_STYLE_SRC',
            field=models.TextField(default="'self' 'unsafe-inline' i.ytimg.com docs.google.com www.youtube-nocookie.com analytics.womensdeclaration.com",
                                   help_text='Specifies valid sources for stylesheets. It would be a security win to disallow unsafe-inline in the future by using a nonce-source/hash-source for any inline styles.'),
        ),
    ]
