# Generated by Django 4.0.10 on 2023-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsecuritypolicysettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
