
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-23T19:16:46+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "c22ecaa78ea0aead1a27bf0403005696bd5c69ad",
 "version": "1.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
