# Generated by Django 3.2.12 on 2023-04-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon_lockout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssession',
            name='successes',
            field=models.IntegerField(default=0),
        ),
    ]
