from .types import Config as Config, FileLike as FileLike, Variable as Variable

def read_config(config: FileLike, preconfig: Config | None = ...) -> Config: ...
def read_configs(filenames: FileLike | list[FileLike], preconfig: Config | None = ...) -> Config: ...
