# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentinel/plan/v1/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from sentinel.types.v1 import status_pb2 as sentinel_dot_types_dot_v1_dot_status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsentinel/plan/v1/events.proto\x12\x10sentinel.plan.v1\x1a\x14gogoproto/gogo.proto\x1a\x1esentinel/types/v1/status.proto\"L\n\x08\x45ventAdd\x12\x19\n\x02id\x18\x01 \x01(\x04\x42\r\xf2\xde\x1f\tyaml:\"id\"\x12%\n\x08provider\x18\x02 \x01(\tB\x13\xf2\xde\x1f\x0fyaml:\"provider\"\"\x90\x01\n\x0e\x45ventSetStatus\x12\x19\n\x02id\x18\x01 \x01(\x04\x42\r\xf2\xde\x1f\tyaml:\"id\"\x12%\n\x08provider\x18\x02 \x01(\tB\x13\xf2\xde\x1f\x0fyaml:\"provider\"\x12<\n\x06status\x18\x03 \x01(\x0e\x32\x19.sentinel.types.v1.StatusB\x11\xf2\xde\x1f\ryaml:\"status\"\"o\n\x0c\x45ventAddNode\x12\x19\n\x02id\x18\x01 \x01(\x04\x42\r\xf2\xde\x1f\tyaml:\"id\"\x12\x1d\n\x04node\x18\x02 \x01(\tB\x0f\xf2\xde\x1f\x0byaml:\"node\"\x12%\n\x08provider\x18\x03 \x01(\tB\x13\xf2\xde\x1f\x0fyaml:\"provider\"\"r\n\x0f\x45ventRemoveNode\x12\x19\n\x02id\x18\x01 \x01(\x04\x42\r\xf2\xde\x1f\tyaml:\"id\"\x12\x1d\n\x04node\x18\x02 \x01(\tB\x0f\xf2\xde\x1f\x0byaml:\"node\"\x12%\n\x08provider\x18\x03 \x01(\tB\x13\xf2\xde\x1f\x0fyaml:\"provider\"B7Z-github.com/sentinel-official/hub/x/plan/types\xa8\xe2\x1e\x00\xc8\xe1\x1e\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentinel.plan.v1.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-github.com/sentinel-official/hub/x/plan/types\250\342\036\000\310\341\036\000'
  _EVENTADD.fields_by_name['id']._options = None
  _EVENTADD.fields_by_name['id']._serialized_options = b'\362\336\037\tyaml:\"id\"'
  _EVENTADD.fields_by_name['provider']._options = None
  _EVENTADD.fields_by_name['provider']._serialized_options = b'\362\336\037\017yaml:\"provider\"'
  _EVENTSETSTATUS.fields_by_name['id']._options = None
  _EVENTSETSTATUS.fields_by_name['id']._serialized_options = b'\362\336\037\tyaml:\"id\"'
  _EVENTSETSTATUS.fields_by_name['provider']._options = None
  _EVENTSETSTATUS.fields_by_name['provider']._serialized_options = b'\362\336\037\017yaml:\"provider\"'
  _EVENTSETSTATUS.fields_by_name['status']._options = None
  _EVENTSETSTATUS.fields_by_name['status']._serialized_options = b'\362\336\037\ryaml:\"status\"'
  _EVENTADDNODE.fields_by_name['id']._options = None
  _EVENTADDNODE.fields_by_name['id']._serialized_options = b'\362\336\037\tyaml:\"id\"'
  _EVENTADDNODE.fields_by_name['node']._options = None
  _EVENTADDNODE.fields_by_name['node']._serialized_options = b'\362\336\037\013yaml:\"node\"'
  _EVENTADDNODE.fields_by_name['provider']._options = None
  _EVENTADDNODE.fields_by_name['provider']._serialized_options = b'\362\336\037\017yaml:\"provider\"'
  _EVENTREMOVENODE.fields_by_name['id']._options = None
  _EVENTREMOVENODE.fields_by_name['id']._serialized_options = b'\362\336\037\tyaml:\"id\"'
  _EVENTREMOVENODE.fields_by_name['node']._options = None
  _EVENTREMOVENODE.fields_by_name['node']._serialized_options = b'\362\336\037\013yaml:\"node\"'
  _EVENTREMOVENODE.fields_by_name['provider']._options = None
  _EVENTREMOVENODE.fields_by_name['provider']._serialized_options = b'\362\336\037\017yaml:\"provider\"'
  _EVENTADD._serialized_start=105
  _EVENTADD._serialized_end=181
  _EVENTSETSTATUS._serialized_start=184
  _EVENTSETSTATUS._serialized_end=328
  _EVENTADDNODE._serialized_start=330
  _EVENTADDNODE._serialized_end=441
  _EVENTREMOVENODE._serialized_start=443
  _EVENTREMOVENODE._serialized_end=557
# @@protoc_insertion_point(module_scope)
