# Generated by Django 3.2.13 on 2022-07-28 15:12

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('content_width_video', '0003_auto_20220621_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentwidthvideo',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
