# Generated by Django 3.2.19 on 2023-06-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_width_video', '0006_merge_20220729_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentwidthvideo',
            name='anchor_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
