from .main import (
    CITATION_OPTIONS,
    DocketReportCitationType,
    extract_docket_from_data,
    extract_dockets,
)
from .regexes import (
    DOCKET_DATE_FORMAT,
    CitationAC,
    CitationAM,
    CitationBM,
    CitationGR,
    CitationJIB,
    CitationOCA,
    CitationPET,
    CitationUDK,
    Docket,
    DocketCategory,
    Num,
    ShortDocketCategory,
    ac_key,
    ac_phrases,
    am_key,
    am_phrases,
    bm_key,
    bm_phrases,
    cull_extra,
    formerly,
    gr_key,
    gr_phrases,
    jib_key,
    jib_phrases,
    l_key,
    oca_key,
    oca_phrases,
    pet_key,
    pet_phrases,
    pp,
    udk_key,
    udk_phrases,
)
from .utils.sc_website_2023 import extract_docket_meta
from .utils.simple_matcher import is_docket, setup_docket_field
