# Generated by Django 4.2.2 on 2023-06-18 10:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TriggerAuditEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_table", models.CharField(max_length=128)),
                ("object_payload", models.TextField()),
                ("audit_entry_created", models.DateTimeField(auto_now_add=True)),
                ("audit_txid_current", models.BigIntegerField()),
                ("audit_operation", models.CharField(max_length=32)),
                ("audit_version", models.IntegerField()),
            ],
            options={
                "db_table": "trigger_audit_entries_v2_view",
                "managed": False,
            },
        ),
    ]
