# Generated by Django 4.0 on 2022-10-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_hrcriteria_trainingemp_tyear_unitcriteria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundType',
            new_name='TType',
        ),
        migrations.DeleteModel(
            name='TrainingType',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.ttype', verbose_name='Tipu'),
        ),
    ]
