# Generated by Django 4.0 on 2022-10-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('training', '0004_trainingplan_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('Unidade', 'Unidade'), ('RH', 'RH')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.CharField(choices=[('Sim', 'Sim'), ('Lae', 'Lae')], max_length=6, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingcriteria', to='training.tcriteria', verbose_name='Pessoal')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingcriteria', to='training.trainingplan')),
                ('training_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingcriteria', to='training.trainingemp', verbose_name='Pessoal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='unitcriteria',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='unitcriteria',
            name='training_emp',
        ),
        migrations.RemoveField(
            model_name='unitcriteria',
            name='user',
        ),
        migrations.DeleteModel(
            name='HRCriteria',
        ),
        migrations.DeleteModel(
            name='UnitCriteria',
        ),
    ]
