# Generated by Django 4.0 on 2022-10-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_remove_trainingplan_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durasaun (loron)'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatin'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Materia Formasaun'),
        ),
    ]
