# Generated by Django 4.0 on 2022-10-26 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_trainingemp_diploma_alter_trainingemp_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcriteria',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingcriteria', to='training.tcriteria', verbose_name='Kriteria'),
        ),
    ]
