# Generated by Django 3.2 on 2022-12-09 17:26

import django.core.validators
from django.db import migrations, models
import settings_app.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_tcriteria_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Kontrato'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Remata'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=settings_app.upload_utils.upload_training, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Upload PDF'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Hahu'),
        ),
    ]
