# Generated by Django 3.2 on 2022-12-10 05:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import settings_app.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom', '0012_alter_department_leader'),
        ('training', '0016_trainingemp_is_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='SProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300, null=True, verbose_name='Titlu Bolso Estudo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data Hahu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Remata')),
                ('target', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatin')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Durasaun (loron)')),
                ('file', models.FileField(blank=True, null=True, upload_to=settings_app.upload_utils.upload_training, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Upload PDF')),
                ('is_lock', models.BooleanField(blank=True, default=False, null=True)),
                ('is_send', models.BooleanField(blank=True, default=False, null=True)),
                ('is_certify', models.BooleanField(blank=True, default=False, null=True)),
                ('is_approve', models.BooleanField(blank=True, default=False, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.country')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.department', verbose_name='Departamentu')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.stype', verbose_name='Tipu Bolso Estudo')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.unit', verbose_name='Unidade')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.university', verbose_name='Universidade')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.tyear', verbose_name='Tinan')),
            ],
        ),
    ]
