# Generated by Django 3.2 on 2023-03-11 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_alter_fidnumber_options'),
        ('training', '0027_traininggap_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggap',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
