# Generated by Django 3.2 on 2023-03-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_alter_fidnumber_options'),
        ('training', '0030_trainingdep_trainingplangap'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplangap',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traininggap', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='traininggap',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainningempgap', to='employee.employee'),
        ),
    ]
