"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import aserto.directory.common.v2.common_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Opcode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OpcodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Opcode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OPCODE_UNKNOWN: _Opcode.ValueType  # 0
    OPCODE_SET: _Opcode.ValueType  # 1
    OPCODE_DELETE: _Opcode.ValueType  # 2

class Opcode(_Opcode, metaclass=_OpcodeEnumTypeWrapper): ...

OPCODE_UNKNOWN: Opcode.ValueType  # 0
OPCODE_SET: Opcode.ValueType  # 1
OPCODE_DELETE: Opcode.ValueType  # 2
global___Opcode = Opcode

@typing_extensions.final
class ImportRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OP_CODE_FIELD_NUMBER: builtins.int
    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    PERMISSION_FIELD_NUMBER: builtins.int
    RELATION_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    op_code: global___Opcode.ValueType
    """operation Opcode enum value"""
    @property
    def object_type(self) -> aserto.directory.common.v2.common_pb2.ObjectType:
        """object_type import message"""
    @property
    def permission(self) -> aserto.directory.common.v2.common_pb2.Permission:
        """permission import message"""
    @property
    def relation_type(self) -> aserto.directory.common.v2.common_pb2.RelationType:
        """relation_type import message"""
    @property
    def object(self) -> aserto.directory.common.v2.common_pb2.Object:
        """object import message"""
    @property
    def relation(self) -> aserto.directory.common.v2.common_pb2.Relation:
        """relation import message"""
    def __init__(
        self,
        *,
        op_code: global___Opcode.ValueType = ...,
        object_type: aserto.directory.common.v2.common_pb2.ObjectType | None = ...,
        permission: aserto.directory.common.v2.common_pb2.Permission | None = ...,
        relation_type: aserto.directory.common.v2.common_pb2.RelationType | None = ...,
        object: aserto.directory.common.v2.common_pb2.Object | None = ...,
        relation: aserto.directory.common.v2.common_pb2.Relation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["msg", b"msg", "object", b"object", "object_type", b"object_type", "permission", b"permission", "relation", b"relation", "relation_type", b"relation_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["msg", b"msg", "object", b"object", "object_type", b"object_type", "op_code", b"op_code", "permission", b"permission", "relation", b"relation", "relation_type", b"relation_type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["msg", b"msg"]) -> typing_extensions.Literal["object_type", "permission", "relation_type", "object", "relation"] | None: ...

global___ImportRequest = ImportRequest

@typing_extensions.final
class ImportResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    PERMISSION_FIELD_NUMBER: builtins.int
    RELATION_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    @property
    def object_type(self) -> global___ImportCounter:
        """object_type import counter"""
    @property
    def permission(self) -> global___ImportCounter:
        """object_type import counter"""
    @property
    def relation_type(self) -> global___ImportCounter:
        """object_type import counter"""
    @property
    def object(self) -> global___ImportCounter:
        """object import counter"""
    @property
    def relation(self) -> global___ImportCounter:
        """object_type import counter"""
    def __init__(
        self,
        *,
        object_type: global___ImportCounter | None = ...,
        permission: global___ImportCounter | None = ...,
        relation_type: global___ImportCounter | None = ...,
        object: global___ImportCounter | None = ...,
        relation: global___ImportCounter | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["object", b"object", "object_type", b"object_type", "permission", b"permission", "relation", b"relation", "relation_type", b"relation_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["object", b"object", "object_type", b"object_type", "permission", b"permission", "relation", b"relation", "relation_type", b"relation_type"]) -> None: ...

global___ImportResponse = ImportResponse

@typing_extensions.final
class ImportCounter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECV_FIELD_NUMBER: builtins.int
    SET_FIELD_NUMBER: builtins.int
    DELETE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    recv: builtins.int
    """number of messages received"""
    set: builtins.int
    """number of messages with OPCODE_SET"""
    delete: builtins.int
    """number of messages with OPCODE_DELETE"""
    error: builtins.int
    """number of messages resulting in error"""
    def __init__(
        self,
        *,
        recv: builtins.int = ...,
        set: builtins.int = ...,
        delete: builtins.int = ...,
        error: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["delete", b"delete", "error", b"error", "recv", b"recv", "set", b"set"]) -> None: ...

global___ImportCounter = ImportCounter
