"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Flag:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FlagEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Flag.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FLAG_UNKNOWN: _Flag.ValueType  # 0
    """default, no special object behavior"""
    FLAG_HIDDEN: _Flag.ValueType  # 1
    """hidden object"""
    FLAG_READONLY: _Flag.ValueType  # 2
    """read-only object"""
    FLAG_SYSTEM: _Flag.ValueType  # 4
    """system object"""
    FLAG_SHADOW: _Flag.ValueType  # 8
    """shadow object by type+key associated to parent object"""

class Flag(_Flag, metaclass=_FlagEnumTypeWrapper): ...

FLAG_UNKNOWN: Flag.ValueType  # 0
"""default, no special object behavior"""
FLAG_HIDDEN: Flag.ValueType  # 1
"""hidden object"""
FLAG_READONLY: Flag.ValueType  # 2
"""read-only object"""
FLAG_SYSTEM: Flag.ValueType  # 4
"""system object"""
FLAG_SHADOW: Flag.ValueType  # 8
"""shadow object by type+key associated to parent object"""
global___Flag = Flag

@typing_extensions.final
class ObjectType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    IS_SUBJECT_FIELD_NUMBER: builtins.int
    ORDINAL_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    SCHEMA_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    name: builtins.str
    """object type name (unique, lc-string)"""
    display_name: builtins.str
    """object type display name"""
    is_subject: builtins.bool
    """object type is a subject (user|group) (default false)"""
    ordinal: builtins.int
    """sort ordinal (default 0)"""
    status: builtins.int
    """status flag bitmap (default 0)"""
    @property
    def schema(self) -> google.protobuf.struct_pb2.Struct:
        """object type schema definition (JSON)"""
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """created at timestamp (UTC)"""
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """last updated timestamp (UTC)"""
    hash: builtins.str
    """object instance hash"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        display_name: builtins.str = ...,
        is_subject: builtins.bool = ...,
        ordinal: builtins.int = ...,
        status: builtins.int = ...,
        schema: google.protobuf.struct_pb2.Struct | None = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        hash: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "schema", b"schema", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "display_name", b"display_name", "hash", b"hash", "is_subject", b"is_subject", "name", b"name", "ordinal", b"ordinal", "schema", b"schema", "status", b"status", "updated_at", b"updated_at"]) -> None: ...

global___ObjectType = ObjectType

@typing_extensions.final
class Permission(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    name: builtins.str
    """permission name (unique, cs-string)"""
    display_name: builtins.str
    """permission display name"""
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """created at timestamp (UTC)"""
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """last updated timestamp (UTC)"""
    hash: builtins.str
    """object instance hash"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        display_name: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        hash: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "display_name", b"display_name", "hash", b"hash", "name", b"name", "updated_at", b"updated_at"]) -> None: ...

global___Permission = Permission

@typing_extensions.final
class RelationType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    ORDINAL_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    UNIONS_FIELD_NUMBER: builtins.int
    PERMISSIONS_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    name: builtins.str
    """relation type name selector"""
    object_type: builtins.str
    """object type referenced by relation"""
    display_name: builtins.str
    """relation display name"""
    ordinal: builtins.int
    """sort ordinal (default 0)"""
    status: builtins.int
    """status bitmap (default 0)"""
    @property
    def unions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """relations union-ed with relation type instance"""
    @property
    def permissions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """permissions associated to relation type instance"""
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """created at timestamp (UTC)"""
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """last updated timestamp (UTC)"""
    hash: builtins.str
    """object instance hash"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        object_type: builtins.str = ...,
        display_name: builtins.str = ...,
        ordinal: builtins.int = ...,
        status: builtins.int = ...,
        unions: collections.abc.Iterable[builtins.str] | None = ...,
        permissions: collections.abc.Iterable[builtins.str] | None = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        hash: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "display_name", b"display_name", "hash", b"hash", "name", b"name", "object_type", b"object_type", "ordinal", b"ordinal", "permissions", b"permissions", "status", b"status", "unions", b"unions", "updated_at", b"updated_at"]) -> None: ...

global___RelationType = RelationType

@typing_extensions.final
class Object(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    key: builtins.str
    """external object key (cs-string)"""
    type: builtins.str
    """object type name"""
    display_name: builtins.str
    """display name object"""
    @property
    def properties(self) -> google.protobuf.struct_pb2.Struct:
        """property bag"""
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """created at timestamp (UTC)"""
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """last updated timestamp (UTC)"""
    hash: builtins.str
    """object instance hash"""
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        type: builtins.str = ...,
        display_name: builtins.str = ...,
        properties: google.protobuf.struct_pb2.Struct | None = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        hash: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "properties", b"properties", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "display_name", b"display_name", "hash", b"hash", "key", b"key", "properties", b"properties", "type", b"type", "updated_at", b"updated_at"]) -> None: ...

global___Object = Object

@typing_extensions.final
class Relation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBJECT_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    OBJECT_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    @property
    def subject(self) -> global___ObjectIdentifier:
        """subject identifier"""
    relation: builtins.str
    """relation type name"""
    @property
    def object(self) -> global___ObjectIdentifier:
        """object identifier"""
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """created at timestamp (UTC)"""
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """last updated timestamp (UTC)"""
    hash: builtins.str
    """object instance hash"""
    def __init__(
        self,
        *,
        subject: global___ObjectIdentifier | None = ...,
        relation: builtins.str = ...,
        object: global___ObjectIdentifier | None = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        hash: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "object", b"object", "subject", b"subject", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "hash", b"hash", "object", b"object", "relation", b"relation", "subject", b"subject", "updated_at", b"updated_at"]) -> None: ...

global___Relation = Relation

@typing_extensions.final
class ObjectDependency(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_KEY_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    SUBJECT_TYPE_FIELD_NUMBER: builtins.int
    SUBJECT_KEY_FIELD_NUMBER: builtins.int
    DEPTH_FIELD_NUMBER: builtins.int
    IS_CYCLE_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    object_type: builtins.str
    """object type name of source object"""
    object_key: builtins.str
    """object search key of source object"""
    relation: builtins.str
    """relation identifier"""
    subject_type: builtins.str
    """object type id of target object"""
    subject_key: builtins.str
    """object search key of target object"""
    depth: builtins.int
    """dependency depth"""
    is_cycle: builtins.bool
    """dependency cycle"""
    @property
    def path(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """dependency path"""
    def __init__(
        self,
        *,
        object_type: builtins.str = ...,
        object_key: builtins.str = ...,
        relation: builtins.str = ...,
        subject_type: builtins.str = ...,
        subject_key: builtins.str = ...,
        depth: builtins.int = ...,
        is_cycle: builtins.bool = ...,
        path: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["depth", b"depth", "is_cycle", b"is_cycle", "object_key", b"object_key", "object_type", b"object_type", "path", b"path", "relation", b"relation", "subject_key", b"subject_key", "subject_type", b"subject_type"]) -> None: ...

global___ObjectDependency = ObjectDependency

@typing_extensions.final
class ObjectTypeIdentifier(google.protobuf.message.Message):
    """ObjectType identifier"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """object type name (unique, lc-string)"""
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_name", b"_name", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_name", b"_name", "name", b"name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_name", b"_name"]) -> typing_extensions.Literal["name"] | None: ...

global___ObjectTypeIdentifier = ObjectTypeIdentifier

@typing_extensions.final
class PermissionIdentifier(google.protobuf.message.Message):
    """Permission identifier"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """permission name (unique, cs-string)"""
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_name", b"_name", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_name", b"_name", "name", b"name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_name", b"_name"]) -> typing_extensions.Literal["name"] | None: ...

global___PermissionIdentifier = PermissionIdentifier

@typing_extensions.final
class RelationTypeIdentifier(google.protobuf.message.Message):
    """RelationType identifier"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    """relation type name selector"""
    object_type: builtins.str
    """object type referenced by relation"""
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        object_type: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_name", b"_name", "_object_type", b"_object_type", "name", b"name", "object_type", b"object_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_name", b"_name", "_object_type", b"_object_type", "name", b"name", "object_type", b"object_type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_name", b"_name"]) -> typing_extensions.Literal["name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_object_type", b"_object_type"]) -> typing_extensions.Literal["object_type"] | None: ...

global___RelationTypeIdentifier = RelationTypeIdentifier

@typing_extensions.final
class ObjectIdentifier(google.protobuf.message.Message):
    """Object identifier"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    type: builtins.str
    """object type"""
    key: builtins.str
    """external object key (cs-string)"""
    def __init__(
        self,
        *,
        type: builtins.str | None = ...,
        key: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_key", b"_key", "_type", b"_type", "key", b"key", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_key", b"_key", "_type", b"_type", "key", b"key", "type", b"type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_key", b"_key"]) -> typing_extensions.Literal["key"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_type", b"_type"]) -> typing_extensions.Literal["type"] | None: ...

global___ObjectIdentifier = ObjectIdentifier

@typing_extensions.final
class RelationIdentifier(google.protobuf.message.Message):
    """Relation identifier"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBJECT_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    OBJECT_FIELD_NUMBER: builtins.int
    @property
    def subject(self) -> global___ObjectIdentifier:
        """subject identifier"""
    @property
    def relation(self) -> global___RelationTypeIdentifier:
        """relation identifier"""
    @property
    def object(self) -> global___ObjectIdentifier:
        """object identifier"""
    def __init__(
        self,
        *,
        subject: global___ObjectIdentifier | None = ...,
        relation: global___RelationTypeIdentifier | None = ...,
        object: global___ObjectIdentifier | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["object", b"object", "relation", b"relation", "subject", b"subject"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["object", b"object", "relation", b"relation", "subject", b"subject"]) -> None: ...

global___RelationIdentifier = RelationIdentifier

@typing_extensions.final
class PaginationRequest(google.protobuf.message.Message):
    """Pagination request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIZE_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    size: builtins.int
    """requested page size, valid value between 1-100 rows (default 100)"""
    token: builtins.str
    """pagination start token, default "" """
    def __init__(
        self,
        *,
        size: builtins.int = ...,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["size", b"size", "token", b"token"]) -> None: ...

global___PaginationRequest = PaginationRequest

@typing_extensions.final
class PaginationResponse(google.protobuf.message.Message):
    """Pagination response"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NEXT_TOKEN_FIELD_NUMBER: builtins.int
    RESULT_SIZE_FIELD_NUMBER: builtins.int
    next_token: builtins.str
    """next page token, when empty there are no more pages to fetch"""
    result_size: builtins.int
    """result size of the page returned"""
    def __init__(
        self,
        *,
        next_token: builtins.str = ...,
        result_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_token", b"next_token", "result_size", b"result_size"]) -> None: ...

global___PaginationResponse = PaginationResponse
