
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-22T10:35:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "43c654b2a19e98650b43aeda7028cfa35dbdb27b",
 "version": "2.2.55"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
