# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-02-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "created_at",
                    models.CharField(default=None, max_length=32, null=True),
                ),
                (
                    "updated_at",
                    models.CharField(default=None, max_length=32, null=True),
                ),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("task_id", models.CharField(max_length=50)),
                ("identifier", models.CharField(max_length=50)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("arguments", models.JSONField(blank=True, null=True)),
                ("keyword_argument", models.JSONField(blank=True, null=True)),
                (
                    "return_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("exception", models.JSONField(blank=True, max_length=100, null=True)),
                ("counter", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
