# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-02-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_remove_task_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.CharField(
                max_length=36, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
