# Generated by Django 3.2.12 on 2022-02-28 10:30

from django.db import migrations, models
import django.db.models.deletion
import giant_plugins.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rich_text_richtext', serialize=False, to='cms.cmsplugin')),
                ('text', giant_plugins.utils.RichTextField(verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
