# Generated by Django 2.2 on 2022-07-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecard',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
