# Generated by Django 4.0 on 2022-10-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_rename_fundtype_ttype_delete_trainingtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durasaun (loron)'),
        ),
    ]
