# Generated by Django 4.0 on 2022-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_tcriteria_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='is_approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='is_certify',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='is_lock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='is_send',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
