# Generated by Django 4.0 on 2022-10-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('training', '0007_trainingplan_is_approve_trainingplan_is_certify_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300, null=True, verbose_name='Materia Formasaun')),
                ('target', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatin')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Durasaun (loron)')),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingsubject', to='training.trainingplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
