# Generated by Django 4.0 on 2022-10-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_trainingsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='place',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='trainingsubject',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='trainingsubject',
            name='hashed',
        ),
        migrations.RemoveField(
            model_name='trainingsubject',
            name='user',
        ),
    ]
