# Generated by Django 4.0 on 2022-10-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_alter_trainingcriteria_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcriteria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
