# Generated by Django 3.2 on 2022-12-10 05:35

import django.core.validators
from django.db import migrations, models
import settings_app.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_scholarshipplan_sprogress_stype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipplan',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='scholarshipplan',
            name='is_approve',
        ),
        migrations.RemoveField(
            model_name='scholarshipplan',
            name='is_certify',
        ),
        migrations.RemoveField(
            model_name='scholarshipplan',
            name='is_send',
        ),
        migrations.RemoveField(
            model_name='scholarshipplan',
            name='target',
        ),
        migrations.AlterField(
            model_name='scholarshipplan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=settings_app.upload_utils.upload_scholarship, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Upload Pareser'),
        ),
    ]
