# Generated by Django 3.2 on 2022-12-10 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0018_auto_20221210_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis', models.CharField(blank=True, max_length=300, null=True, verbose_name='Thesis')),
                ('is_lock', models.BooleanField(blank=True, default=False, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarshipemp', to='training.trainingemp', verbose_name='Pessoal')),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarshipemp', to='training.scholarshipplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipEmpProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('is_lock', models.BooleanField(blank=True, default=False, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.sprogress')),
                ('scholarshipemp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarshipempprogress', to='training.scholarshipemp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
