# Generated by Django 3.2 on 2022-12-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_scholarshipemp_scholarshipempprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipplan',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='scholarshipplan',
            name='unit',
        ),
    ]
