# Generated by Django 3.2 on 2022-12-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20221210_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarshipempprogress',
            old_name='start_date',
            new_name='date',
        ),
    ]
