# Generated by Django 3.2 on 2022-12-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_alter_scholarshipemp_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipplan',
            name='is_update',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
