# Generated by Django 3.2 on 2023-02-14 03:45

import django.core.validators
from django.db import migrations, models
import settings_app.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_auto_20221210_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingemp',
            name='subject',
            field=models.FileField(blank=True, null=True, upload_to=settings_app.upload_utils.upload_training_subject, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Upload Materia'),
        ),
    ]
