# Generated by Django 3.2 on 2023-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_traininggap_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggap',
            name='is_lock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
