# Generated by Django 2.2 on 2022-06-21 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_width_video', '0002_contentwidthvideo_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentwidthvideo',
            name='caption',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='contentwidthvideo',
            name='youtube_url',
            field=models.URLField(blank=True, help_text="\n            Enter the full URL of the youtube video page. \n            To start the video at a specific time add '?start=xx' to the end of the url (using seconds). \n            You can also add extra paramaters using an ampersand, for example '?start=75&autoplay=1'.\n        ", null=True, validators=[django.core.validators.URLValidator(message='Please enter the full URL of the Youtube video page', regex='www.youtube.com', schemes=['https'])]),
        ),
    ]
