# Generated by Django 3.2.13 on 2022-07-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_width_video", "0004_alter_contentwidthvideo_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentwidthvideo",
            name="alt_title",
        ),
    ]
