# Generated by Django 3.2.13 on 2022-07-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_width_video', '0004_alter_contentwidthvideo_youtube_url'),
        ('content_width_video', '0005_remove_contentwidthvideo_alt_title'),
    ]

    operations = [
    ]
