VERSION_YEAR = 2023
VERSION_MONTH = int('06')
VERSION_DAY = int('23')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('44')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202306231244
version_date = '2023/06/23 12:44'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
