# Generated by Django 2.2 on 2022-05-30 03:56

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('pullquote', '0002_auto_20220407_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullquote',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Choose an optional image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
