# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sample_py',
                'doc_host': 'https://RyanMcCarthy.github.io',
                'git_url': 'https://github.com/RyanMcCarthy/sample_py',
                'lib_path': 'sample_py'},
  'syms': {'sample_py.core': {'sample_py.core.foo': ('physics_inf.html#foo', 'sample_py/core.py')}}}
