# Generated by Django 2.2 on 2022-05-30 03:56

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('logo_grid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logocard',
            name='logo',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logo', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
